### PR TITLE
AltBeacon Reference

### PR DESCRIPTION
**Pull request by jnebeker**
I decided to transmit with null identifiers and with a fake company identifier of 0x001 (to show the endianness).    I'm open to feedback about that and the short name (MAN_DATA) I use for the "AD Data - Manufacturer Reserved". I also split the leading four bytes of the advertisement from the "AltBeacon standard" to make the difference clear, but the wording might need adjustment (e.g., "Bluetooth LE Prefix").  I plan on updating the comments to reflect the wording we use on the final AltBeacon spec.

### CODE REVIEW

**Comment by davidgyoung** [comment]
Looks good!  The 0x0001 company code is assigned to Nokia, see here: https://www.bluetooth.org/en-us/specification/assigned-numbers/company-identifiers, so I think we should probably just use Radius as the example.  We can add a comment about endianness.

**Comment by davidgyoung** [comment]
Comment might also say "please substitute your assigned manufacturer code, if available."

**Comment by csexton** [comment]
I am not quite sure what "man data" is. :see_no_evil:

**Comment by jnebeker** [comment]
The name could use some work, but I think we should come up with something so we don't have to call it "AD Data - Manufacturer Reserved" every time (i.e., UUID, major, minor, ID1, ID2, ID3, etc.).  But this discussion probably belongs in the altbecon-spec repo anyways.

**Comment by csexton** [comment]
Nah, it's just fine. I thought it was funny.

**Pull request merged**
